# Generated by Django 2.0.4 on 2018-08-22 22:47

from django.db import migrations
import csv
import os


def load_data(apps, schema_editor):
    Hero = apps.get_model('api', 'Hero')
    with open(os.path.dirname(os.path.abspath(__file__)) + '/data/hero.csv', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            hero, _ = Hero.objects.get_or_create(id=row['id'])
            hero.name = row['name']
            hero.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
